local_sync_client:

  users:
    - username: "asier"
      email: "asier@email.com"
      key_location: "/path/to/key"
      local_sotorage_paths:
        - "/home/asier/Personal_cloud/local_storage_1"
        - "/home/asier/Personal_cloud/local_storage_2"

    - username: "asier2"
      email: "asier@email.com"
      key_location: "/path/to/key"
      local_sotorage_paths:
        - "/home/asier/Personal_cloud/local_storage_1"
        - "/home/asier/Personal_cloud/local_storage_2"